#ifndef NILE_KERNEL_IO_BLOCK_DEV_H_
#define NILE_KERNEL_IO_BLOCK_DEV_H_

//Never include this file directly, include nile/kernel/io_dev.h

#include "nile/stdtypes.h"
#include "nile/kernel/io_op_queue.h"

#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_READY_POS          NILE_KERNEL_IO_DEV_FLAG_DEV_READY_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_BLOCK_DEV_POS      NILE_KERNEL_IO_DEV_FLAG_DEV_BLOCK_DEV_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_CHAR_DEV_POS       NILE_KERNEL_IO_DEV_FLAG_DEV_CHAR_DEV_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_TX_ENABLED_POS     NILE_KERNEL_IO_DEV_FLAG_DEV_TX_ENABLED_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_RX_ENABLED_POS     NILE_KERNEL_IO_DEV_FLAG_DEV_RX_ENABLED_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_EX_ENABLED_POS     NILE_KERNEL_IO_DEV_FLAG_DEV_EX_ENABLED_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_HW_ACTIVE_POS      NILE_KERNEL_IO_DEV_FLAG_DEV_HW_ACTIVE_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_HW_TX_ACTIVE_POS   NILE_KERNEL_IO_DEV_FLAG_DEV_HW_TX_ACTIVE_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_HW_RX_ACTIVE_POS   NILE_KERNEL_IO_DEV_FLAG_DEV_HW_RX_ACTIVE_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_MEMMAPPED_POS      NILE_KERNEL_IO_DEV_FLAG_DEV_MEMMAPPED_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_SHARED_POS         NILE_KERNEL_IO_DEV_FLAG_DEV_SHARED_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_ERROR_CODE_POS     NILE_KERNEL_IO_DEV_FLAG_DEV_ERROR_CODE_POS
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_ERROR_POS          NILE_KERNEL_IO_DEV_FLAG_DEV_ERROR_POS


#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_READY              NILE_KERNEL_IO_DEV_FLAG_DEV_READY
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_BLOCK_DEV          NILE_KERNEL_IO_DEV_FLAG_DEV_BLOCK_DEV
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_CHAR_DEV           NILE_KERNEL_IO_DEV_FLAG_DEV_CHAR_DEV
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_TX_ENABLED         NILE_KERNEL_IO_DEV_FLAG_DEV_TX_ENABLED
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_RX_ENABLED         NILE_KERNEL_IO_DEV_FLAG_DEV_RX_ENABLED
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_EX_ENABLED         NILE_KERNEL_IO_DEV_FLAG_DEV_EX_ENABLED
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_HW_ACTIVE          NILE_KERNEL_IO_DEV_FLAG_DEV_HW_ACTIVE
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_HW_TX_ACTIVE       NILE_KERNEL_IO_DEV_FLAG_DEV_HW_TX_ACTIVE
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_HW_RX_ACTIVE       NILE_KERNEL_IO_DEV_FLAG_DEV_HW_RX_ACTIVE
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_MEMMAPPED          NILE_KERNEL_IO_DEV_FLAG_DEV_MEMMAPPED
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_SHARED             NILE_KERNEL_IO_DEV_FLAG_DEV_SHARED
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_ERROR_CODE_MASK    NILE_KERNEL_IO_DEV_FLAG_DEV_ERROR_CODE_MASK
#define NILE_KERNEL_IO_BLOCK_DEV_FLAG_DEV_ERROR              NILE_KERNEL_IO_DEV_FLAG_DEV_ERROR



#define NILE_KERNEL_IO_BLOCK_DEV_GRN_TOTAL_POS          (0)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_MEM_WIDTH_POS      (8)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_WIDTH_POS      (10)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_RESERVED_POS       (12)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_AUTOINC_POS    (14)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DYNAMIC_POS        (15)

#define NILE_KERNEL_IO_BLOCK_DEV_GRN_TOTAL_MASK         (0xFFU << NILE_KERNEL_IO_BLOCK_DEV_GRN_TOTAL_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_MEM_WIDTH_MASK     (0x03U << NILE_KERNEL_IO_BLOCK_DEV_GRN_MEM_WIDTH_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_WIDTH_MASK     (0x03U << NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_WIDTH_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_RESERVED_MASK      (0x03U << NILE_KERNEL_IO_BLOCK_DEV_GRN_RESERVED_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_AUTOINC_MASK   (1U << NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_AUTOINC_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DYNAMIC_MASK       (1U << NILE_KERNEL_IO_BLOCK_DEV_GRN_DYNAMIC_POS)

#define NILE_KERNEL_IO_BLOCK_DEV_GRN_MEM_WIDTH_8        (0U << NILE_KERNEL_IO_BLOCK_DEV_GRN_MEM_WIDTH_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_MEM_WIDTH_16       (1U << NILE_KERNEL_IO_BLOCK_DEV_GRN_MEM_WIDTH_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_MEM_WIDTH_32       (2U << NILE_KERNEL_IO_BLOCK_DEV_GRN_MEM_WIDTH_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_MEM_WIDTH_64       (3U << NILE_KERNEL_IO_BLOCK_DEV_GRN_MEM_WIDTH_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_WIDTH_8        (0U << NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_WIDTH_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_WIDTH_16       (1U << NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_WIDTH_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_WIDTH_32       (2U << NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_WIDTH_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_WIDTH_64       (3U << NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_WIDTH_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_AUTOINC        (1u << NILE_KERNEL_IO_BLOCK_DEV_GRN_DEV_AUTOINC_POS)
#define NILE_KERNEL_IO_BLOCK_DEV_GRN_DYNAMIC            (1u << NILE_KERNEL_IO_BLOCK_DEV_GRN_DYNAMIC_POS)

typedef struct nile_kernel_io_block_dev{
	uint32_t flags;
	void* hw;
	void (*hw_init)(struct nile_kernel_io_block_dev* dev);
	void (*hw_reset)(struct nile_kernel_io_block_dev* dev);
	void (*hw_stop)(struct nile_kernel_io_block_dev* dev);
	void (*rqx_execute)(struct nile_kernel_io_block_dev* dev);
	void (*hw_memmapped_enable)(struct nile_kernel_io_block_dev* dev);
	void (*hw_memmapped_disable)(struct nile_kernel_io_block_dev* dev);
	nile_kernel_io_block_dev_op_queue* rqx;
	void* rx_memmap_addr;
	void* tcb_owner;
	volatile void *hw_tx_data_reg;
	volatile void *hw_rx_data_reg;
	uint32_t capacity;
	uint32_t read_block_size;
	uint32_t write_block_size;
	uint32_t erase_block_size;
	uint16_t read_granularity;
	uint16_t write_granularity;
	void* additional_data;
	uint32_t additional_data_bytelen;
}nile_kernel_io_block_dev;


#endif /* NILE_KERNEL_IO_BLOCK_DEV_H_ */
