#ifndef NILE_KERNEL_IO_DEV_H_
#define NILE_KERNEL_IO_DEV_H_

#define IO_HW_OP_FINISHED_CODE_OP_LENGTH_POS       (0)
#define IO_HW_OP_FINISHED_CODE_OP_LENGTH_MASK      (0x00FFFFFFUL << IO_HW_OP_FINISHED_CODE_OP_LENGTH_POS)
#define IO_HW_OP_FINISHED_CODE_ERRCODE_POS         (24)
#define IO_HW_OP_FINISHED_CODE_ERRCODE_MASK        (0x7F000000UL << IO_HW_OP_FINISHED_CODE_ERRCODE_POS)

enum{
    IO_HW_OP_FINISHED_CODE_ERRCODE_NONE = 0,
	IO_HW_OP_FINISHED_CODE_ERRCODE_ABORTED,


};
/* Bit positions */
#define NILE_KERNEL_IO_DEV_FLAG_DEV_READY_POS          0U
#define NILE_KERNEL_IO_DEV_FLAG_DEV_BLOCK_DEV_POS      1U
#define NILE_KERNEL_IO_DEV_FLAG_DEV_CHAR_DEV_POS       2U
#define NILE_KERNEL_IO_DEV_FLAG_DEV_TX_ENABLED_POS     3U
#define NILE_KERNEL_IO_DEV_FLAG_DEV_RX_ENABLED_POS     4U
#define NILE_KERNEL_IO_DEV_FLAG_DEV_EX_ENABLED_POS     5U
#define NILE_KERNEL_IO_DEV_FLAG_DEV_HW_ACTIVE_POS      6U
#define NILE_KERNEL_IO_DEV_FLAG_DEV_HW_TX_ACTIVE_POS   7U
#define NILE_KERNEL_IO_DEV_FLAG_DEV_HW_RX_ACTIVE_POS   8U

#define NILE_KERNEL_IO_DEV_FLAG_DEV_MEMMAPPED_POS      22U
#define NILE_KERNEL_IO_DEV_FLAG_DEV_SHARED_POS         23U

#define NILE_KERNEL_IO_DEV_FLAG_DEV_ERROR_CODE_POS     24U
#define NILE_KERNEL_IO_DEV_FLAG_DEV_ERROR_POS          31U

/* Flags */
#define NILE_KERNEL_IO_DEV_FLAG_DEV_READY          (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_READY_POS)
#define NILE_KERNEL_IO_DEV_FLAG_DEV_BLOCK_DEV      (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_BLOCK_DEV_POS)
#define NILE_KERNEL_IO_DEV_FLAG_DEV_CHAR_DEV       (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_CHAR_DEV_POS)
#define NILE_KERNEL_IO_DEV_FLAG_DEV_TX_ENABLED     (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_TX_ENABLED_POS)
#define NILE_KERNEL_IO_DEV_FLAG_DEV_RX_ENABLED     (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_RX_ENABLED_POS)
#define NILE_KERNEL_IO_DEV_FLAG_DEV_EX_ENABLED     (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_EX_ENABLED_POS)
#define NILE_KERNEL_IO_DEV_FLAG_DEV_HW_ACTIVE      (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_HW_ACTIVE_POS)
#define NILE_KERNEL_IO_DEV_FLAG_DEV_HW_TX_ACTIVE   (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_HW_TX_ACTIVE_POS)
#define NILE_KERNEL_IO_DEV_FLAG_DEV_HW_RX_ACTIVE   (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_HW_RX_ACTIVE_POS)

#define NILE_KERNEL_IO_DEV_FLAG_DEV_MEMMAPPED      (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_MEMMAPPED_POS)
#define NILE_KERNEL_IO_DEV_FLAG_DEV_SHARED         (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_SHARED_POS)

/* Error code mask (7 bits starting at bit 24) */
#define NILE_KERNEL_IO_DEV_FLAG_DEV_ERROR_CODE_MASK (0x7FU << NILE_KERNEL_IO_DEV_FLAG_DEV_ERROR_CODE_POS)

#define NILE_KERNEL_IO_DEV_FLAG_DEV_ERROR          (1U << NILE_KERNEL_IO_DEV_FLAG_DEV_ERROR_POS)

#include "io_char_dev.h"
#include "io_block_dev.h"

#endif
