#ifndef APP_IO_DEV_IRQ_PRIORITY_H_
#define APP_IO_DEV_IRQ_PRIORITY_H_

#include "nile/irq_priority.h"

#define UART1_IRQ_LEVEL NILE_IRQ_PRIO_LVL_USR_0
#define UART2_IRQ_LEVEL NILE_IRQ_PRIO_LVL_USR_0
#define UART3_IRQ_LEVEL NILE_IRQ_PRIO_LVL_USR_0
#define UART4_IRQ_LEVEL NILE_IRQ_PRIO_LVL_USR_0
#define UART5_IRQ_LEVEL NILE_IRQ_PRIO_LVL_USR_0
#define UART6_IRQ_LEVEL NILE_IRQ_PRIO_LVL_USR_0
#define UART7_IRQ_LEVEL NILE_IRQ_PRIO_LVL_USR_0
#define UART8_IRQ_LEVEL NILE_IRQ_PRIO_LVL_USR_0

#define QUADSPI_IRQ_LEVEL  NILE_IRQ_PRIO_LVL_USR_1

#endif /* APP_IO_DEV_IRQ_PRIORITY_H_ */
