#ifndef NILE_MCU_STM32F746_KERNEL_CONFIG_H_
#define NILE_MCU_STM32F746_KERNEL_CONFIG_H_

#define MCU_MAX_CPU_FREQUENCY			(216000000UL)
#undef  MCU_INIT_CPU_FREQUENCY
#define MCU_INIT_CPU_FREQUENCY          MCU_MAX_CPU_FREQUENCY


#endif /* NILE_MCU_STM32F746_KERNEL_CONFIG_H_ */
